*&---------------------------------------------------------------------*
*& Include          ZC2MMR2001_S01
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK bl1 WITH FRAME TITLE titel.

  SELECTION-SCREEN SKIP 1.
* SELECTION-SCREEN ULINE.

  PARAMETERS     : pa_plant TYPE c LENGTH 4 DEFAULT '1000' MODIF ID md1.


  SELECTION-SCREEN BEGIN OF LINE.

    SELECTION-SCREEN COMMENT (31) TEXT-007 FOR FIELD pa_vendo MODIF ID md1.

    PARAMETERS :  pa_vendo TYPE ztc2md2005-vendorc MODIF ID md1.
    SELECTION-SCREEN COMMENT (10) p_venn MODIF ID md1.

  SELECTION-SCREEN END OF LINE.







  PARAMETERS : pa_plan2 TYPE c LENGTH 4 DEFAULT '1000' MODIF ID md2.

  SELECTION-SCREEN BEGIN OF LINE.

    SELECTION-SCREEN COMMENT (28) TEXT-007 FOR FIELD so_vend MODIF ID md2.

     SELECT-OPTIONS : so_vend  FOR ztc2md2005-vendorc  NO-EXTENSION NO INTERVALS MODIF ID md2.

    SELECTION-SCREEN COMMENT (10) p_venn2 MODIF ID md2.

  SELECTION-SCREEN END OF LINE.

  SELECT-OPTIONS : so_orpd  FOR ztc2mm2004-orpddt       NO-EXTENSION MODIF ID md2 ,
                   so_flag  FOR gs_status_flag-statflag NO-EXTENSION NO INTERVALS MODIF ID md2.





 PARAMETERS : pa_plan3 TYPE c LENGTH 4 DEFAULT '1000' MODIF ID md6.

  SELECTION-SCREEN BEGIN OF LINE.

    SELECTION-SCREEN COMMENT (28) TEXT-007 FOR FIELD so_vend2 MODIF ID md6.

     SELECT-OPTIONS : so_vend2  FOR ztc2md2005-vendorc  NO-EXTENSION NO INTERVALS MODIF ID md6.

    SELECTION-SCREEN COMMENT (10) p_venn3 MODIF ID md6.

  SELECTION-SCREEN END OF LINE.

  SELECT-OPTIONS : so_orpd2  FOR ztc2mm2004-orpddt       NO-EXTENSION MODIF ID md6 ,
                   so_flag2  FOR gs_status_flag-statflag NO-EXTENSION NO INTERVALS MODIF ID md6.



SELECTION-SCREEN END OF BLOCK bl1.


SELECTION-SCREEN BEGIN OF BLOCK bl2 WITH FRAME TITLE TEXT-002.

  PARAMETERS : ra_cre  RADIOBUTTON GROUP rdg DEFAULT 'X' MODIF ID md3 USER-COMMAND radio1,
               ra_vie  RADIOBUTTON GROUP rdg MODIF ID md4,
               ra_vie2 RADIOBUTTON GROUP rdg MODIF ID md5.

SELECTION-SCREEN END OF BLOCK bl2.